bruin = set({'Boxtel', 'Best', 'Beukenlaan', 'Eindhoven', "Helmond 't Hout", 'Helmond', 'Helmond Brouwhuis', 'Deurne'})
groen = set({'Boxtel', 'Best', 'Beukenlaan', 'Eindhoven', 'Geldrop', 'Heeze', 'Weert'})
print(bruin.intersection(groen))
print(bruin.difference(groen))
print(bruin.union(groen))